### PR TITLE
Flutter 1.20.0 compatibility and improved test parsing

### PR DESCRIPTION
**Pull request by kuhnroyal**
* add support for Flutter 1.20.0 which emits empty lines and debug events
* parse JSON events based on their type which is documented here: https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md
*  restore Java 8 compatibility by removing `Path.of()` usage
* use Scanner to read lines from file or String which should handle line endings correctly
* do not report hidden tests, those are generated for setUp/tearDown functions - this previously resulted in way to many reported test cases 
* correctly determine the test duration, the outpout does not contain the duration but a start time and end time for each testID

* add maven wrapper to ease development

### CODE REVIEW

**Comment by kuhnroyal** [comment]
@stephanecodes Could you review this please and see if that also solves your nullpointer problem. 

I am using this together with your change for the analysis file.

**Comment by stephanecodes** [comment]
Correct me if I'm wrong as I did not test 1.20 yet but I already fixed the NullPointerException in #22 
I'll review your code btw asap, it includes some interesting stuffs

**Comment by kuhnroyal** [comment]
Yes you did, I used your commit initially but I needed more changes.

**Comment by zippy1978** [comment]
@kuhnroyal, @stephanecodes thanks for your contribution !
Seems perfect 👌

**Pull request merged**
