### PR TITLE
Fix regex, path and etc

### PR DESCRIPTION
**Pull request by victorgilc**
Reach for any questions and appointments

### CODE REVIEW

**Comment by zippy1978** [comment]
Thank you @victorgilc !
I had a look at the PR but it seems some file updates are missing (at least FlutterUnitTest.java)

**Comment by victorgilc** [comment]
> Thank you @victorgilc !
> I had a look at the PR but it seems some file updates are missing (at least FlutterUnitTest.java)

Hello Gilles.

I did the merge between my branch and the develop branch, now I think it's ok, thanks!

**Comment by zippy1978** [comment]
Thanks again !

**Comment by zippy1978** [comment]
Hi @victorgilc,

Just to let you know : I had to fix some issues on DartAnalyzerSensor after the merge : 
- File paths were broken on Unix / macOS
- There was a problem with the default analysis options file not being created / restored properly (resulted in no issue reported)

I pushed the fix on develop, it should be fine now.

**Comment by victorgilc** [comment]
> Hi @victorgilc,
> 
> Just to let you know : I had to fix some issues on DartAnalyzerSensor after the merge :
> 
> * File paths were broken on Unix / macOS
> * There was a problem with the default analysis options file not being created / restored properly (resulted in no issue reported)
> 
> I pushed the fix on develop, it should be fine now.

Hello Gilles.

Testing on Windows, there's something wrong yet:

20:15:09.384 ERROR: Failed to parse test report
java.io.FileNotFoundException: D:\workspace\samples-master\platform_design\tests.output (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(Unknown Source)
        at java.base/java.io.FileInputStream.<init>(Unknown Source)
        at java.base/java.util.Scanner.<init>(Unknown Source)
        at java.base/java.util.Scanner.<init>(Unknown Source)
        at fr.insideapp.sonarqube.flutter.tests.FlutterTestReportParser.parse(FlutterTestReportParser.java:43)
        at fr.insideapp.sonarqube.flutter.tests.FlutterTestSensor.execute(FlutterTestSensor.java:57)

20:15:09.369 ERROR: For input string: "\workspace\samples-master\platform_design\lib\profile_tab.dart D"
java.lang.NumberFormatException: For input string: "\workspace\samples-master\platform_design\lib\profile_tab.dart D"
        at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.base/java.lang.Integer.parseInt(Unknown Source)
        at java.base/java.lang.Integer.parseInt(Unknown Source)
        at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerReportParser.parse(DartAnalyzerReportParser.java:39)
        at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerSensor.buildIssues(DartAnalyzerSensor.java:134)
        at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerSensor.execute(DartAnalyzerSensor.java:75)

**Comment by zippy1978** [comment]
Hello,

For the first one : did you run `flutter test --machine > tests.output` to generate the test report before ?

For the second one : the way Windows paths are parsed in dartanalzer output is KO.
I suspect this `Pattern pattern = Pattern.compile("(.*)(-|•)(.*)(-|•)(.*):(.*):(.*)(-|•)(.*)");` to be confused with `:` in Windows file paths.

However as I don't have any Windows machine, could you give me an example output of dartanalyzer on Windows ? 
So that I can write a unit test to make it work.

**Comment by victorgilc** [comment]
Yeah, you are right.

I created this new PR: https://github.com/insideapp-oss/sonar-flutter/pull/27

Thanks man.

**Pull request merged**
