### PR TITLE
Restored sonar.dart.analysis.reportPath functionality that must have …

### PR DESCRIPTION
**Pull request by iilievdev**
…been accidentally removed.

https://github.com/insideapp-oss/sonar-flutter/issues/169

### CODE REVIEW

**Comment by iilievdev** [comment]
@zippy1978  please take a look as I see you are working on improvements for a new release, this property is in the official documentation:

`# Allows reuse of an existing analyzer report
# sonar.dart.analysis.reportPath=`

It is also part of the configuration but the code handling it has disappeared between two commits without a comment, I just restored it from the original commit. This should also close issue https://github.com/insideapp-oss/sonar-flutter/issues/169

**Comment by zippy1978** [comment]
Thank you @iilievdev 
I'll merge it back to develop soon !

**Comment by iilievdev** [comment]
Ah sure, @zippy1978  changed base branch to develop here as well

**Comment by zippy1978** [comment]
Hi @iilievdev ,

I finished working on a big cleanup since last release and integrated pending improvements.

And `sonar.dart.analysis.reportPath` mechanism is actually still there, but was changed a bit.

`sonar.dart.analysis.reportPath` is renamed to `sonar.dart.analyzer.report.path`.
And is picked up only if you set `sonar.dart.analyzer.mode=MANUAL`

Have a look at the README on the develop branch for more context.

I should release a 0.5.0 version in the days to come, but in the meantime you can test it with the snapshot release here: https://github.com/insideapp-oss/sonar-flutter/releases/tag/0.5.0-SNAPSHOT

**Comment by iilievdev** [comment]
Ah, I see, I was looking at the code for 0.4.0 release and saw it was missing there, did not check develop, I see that it is back in full force, I'll wait for the release and i'll just close this for now

**Pull request closed without merging**
